### ISSUE TITLE
'module' object has no attribute 'Ga' (brombo/galgebra#12)

### ISSUE THREAD

**Issue by eric-wieser** [pygae/galgebra#106]
@utensil commented on May 1, 2016

<blockquote>
          <h2>Enviroment</h2>
<ul>
<li>MacBook Pro (Retina, 13-inch, Mid 2014)</li>
<li>OSX 10.11.2</li>
<li>Python 2.7.11</li>
<li>numpy 1.9.2</li>
<li>sympy 1.0</li>
</ul>
<h2>Steps</h2>
<pre><code>git clone https://github.com/brombo/galgebra.git
cd galgebra
python setup.py install
python setup.py test
</code></pre>
<div class="highlight highlight-source-python"><pre><span class="pl-k">import</span> galgebra
galgebra.Ga</pre></div>
<h2>Error</h2>
<pre><code>Traceback (most recent call last):
  File "&lt;stdin&gt;", line 1, in &lt;module&gt;
AttributeError: 'module' object has no attribute 'Ga'
</code></pre>
<p>If I <code>import ga</code> instead, got</p>
<pre><code>Traceback (most recent call last):
  File "&lt;stdin&gt;", line 1, in &lt;module&gt;
ImportError: No module named ga
</code></pre>
<p>I looked into examples and tests, and can't figure out what went wrong.</p>
      </blockquote>

@brombo commented on May 1, 2016

<blockquote>
          <p>"python setup.py test" not implemented (I don't really know hot to write<br>
a setup.py file).  You would need to run tests and examples manually<br>
(one at a time).  Also "test_test.py" uses old GA format and was not<br>
converted when I left sympy distribution.  There is no more module MV to<br>
import. Will fix<br>
test_test.py when I get time.  In examples Terminal/terminal_check.py<br>
and LaTeX/latex_check.py run same tests and more without asserts<br>
(answers printed out).</p>
      </blockquote>

@utensil commented on May 1, 2016 • 
edited 

<blockquote>
          <p>Oh it's not about the tests. I saw 0 tests were run.<br>
Just that I can't use any classes in "ga" or "galgebra" after importing either of them in REPL.</p>
      </blockquote>

@utensil commented on May 1, 2016

<blockquote>
          <p>Let's use exact code from "Terminal/terminal_check.py":</p>
<div class="highlight highlight-source-python"><pre><span class="pl-ii">$</span> python
Python <span class="pl-c1">2.7</span>.11 <span class="pl-k">|</span>Continuum Analytics, Inc.<span class="pl-k">|</span> (default, Dec  <span class="pl-c1">6</span> <span class="pl-c1">2015</span>, <span class="pl-c1">18</span>:<span class="pl-c1">57</span>:<span class="pl-c1">58</span>) 
[<span class="pl-c1">GCC</span> <span class="pl-c1">4.2</span>.1 (Apple Inc. build <span class="pl-c1">5577</span>)] on darwin
Type <span class="pl-s"><span class="pl-pds">"</span>help<span class="pl-pds">"</span></span>, <span class="pl-s"><span class="pl-pds">"</span>copyright<span class="pl-pds">"</span></span>, <span class="pl-s"><span class="pl-pds">"</span>credits<span class="pl-pds">"</span></span> <span class="pl-k">or</span> <span class="pl-s"><span class="pl-pds">"</span>license<span class="pl-pds">"</span></span> <span class="pl-k">for</span> more information.
Anaconda <span class="pl-k">is</span> brought to you by Continuum Analytics.
Please check out: http:<span class="pl-k">//</span>continuum.io<span class="pl-k">/</span>thanks <span class="pl-k">and</span> https:<span class="pl-k">//</span>anaconda.org
<span class="pl-k">&gt;&gt;</span><span class="pl-k">&gt;</span> <span class="pl-k">from</span> ga <span class="pl-k">import</span> Ga, one, zero
Traceback (most recent call last):
  File <span class="pl-s"><span class="pl-pds">"</span>&lt;stdin&gt;<span class="pl-pds">"</span></span>, line <span class="pl-c1">1</span>, <span class="pl-k">in</span> <span class="pl-k">&lt;</span>module<span class="pl-k">&gt;</span>
<span class="pl-c1">ImportError</span>: No module named ga
<span class="pl-k">&gt;&gt;</span><span class="pl-k">&gt;</span> <span class="pl-k">from</span> galgebra <span class="pl-k">import</span> Ga, one, zero
Traceback (most recent call last):
  File <span class="pl-s"><span class="pl-pds">"</span>&lt;stdin&gt;<span class="pl-pds">"</span></span>, line <span class="pl-c1">1</span>, <span class="pl-k">in</span> <span class="pl-k">&lt;</span>module<span class="pl-k">&gt;</span>
<span class="pl-c1">ImportError</span>: cannot <span class="pl-k">import</span> name Ga</pre></div>
      </blockquote>

@brombo commented on May 1, 2016

<blockquote>
          <p>To install use the instructions starting on page 5 of galgebra.pdf in<br>
the doc directory (specifically section 1.3 in the doc) not setup.py.<br>
Note that the Ipython notebook install section is dated.</p>
      </blockquote>

@utensil commented on May 2, 2016

<blockquote>
          <p>I followed the instructions in galgebra.pdf, still no luck:</p>
<div class="highlight highlight-source-shell"><pre>galgebra $ <span class="pl-c1">pwd</span>
/Users/utensil/experiments/galgebra/galgebra
galgebra $ ls
__init__.py __init__.pyc    ga.py       lt.py       metric.py   mv.py       printer.py  setgapth.py
galgebra $ python setgapth.py
Traceback (most recent call last):
  File <span class="pl-s"><span class="pl-pds">"</span>setgapth.py<span class="pl-pds">"</span></span>, line 28, <span class="pl-k">in</span> <span class="pl-k">&lt;</span>module<span class="pl-k">&gt;</span>
    pth_file = open(pth_name,<span class="pl-s"><span class="pl-pds">'</span>w<span class="pl-pds">'</span></span>)
IOError: [Errno 2] No such file or directory: <span class="pl-s"><span class="pl-pds">'</span>/Users/utensil/miniconda2/lib/site-python/Ga.pth<span class="pl-pds">'</span></span>
galgebra $ ls /Users/utensil/miniconda2/lib/site-python/
ls: /Users/utensil/miniconda2/lib/site-python/: No such file or directory
galgebra $ ls /Users/utensil/miniconda2/lib/
Tk.icns                 libQtScript.4.dylib         libmkl_avx2.dylib
Tk.tiff                 libQtScript.dylib           libmkl_avx512.dylib
engines                 libQtScript.la              libmkl_core.dylib
libQtCLucene.4.8.7.dylib        libQtScript.prl             libmkl_intel.dylib</pre></div>
      </blockquote>

@utensil commented on May 2, 2016

<blockquote>
          <p>After manually created the directory:</p>
<div class="highlight highlight-source-shell"><pre>mkdir <span class="pl-s"><span class="pl-pds">'</span>/Users/utensil/miniconda2/lib/site-python<span class="pl-pds">'</span></span>
galgebra $ python setgapth.py
os name: posix
site-packages directory: /Users/utensil/miniconda2/lib/site-python/Ga.pth
Ga.pth:
<span class="pl-c"><span class="pl-c">#</span>Path of Ga module</span>
/Users/utensil/experiments/galgebra/galgebra
0

Python pth file Ga.pth <span class="pl-k">for</span> all modules of galgebra has been created and
placed <span class="pl-k">in</span> directory appropriate <span class="pl-k">for</span> Linux, Windows, or OSX.  Note that
<span class="pl-k">if</span> Ga.pth already exists the old version will be deleted.</pre></div>
<div class="highlight highlight-source-python"><pre><span class="pl-k">&gt;&gt;</span><span class="pl-k">&gt;</span> <span class="pl-k">import</span> ga
<span class="pl-k">&gt;&gt;</span><span class="pl-k">&gt;</span> ga.Ga
<span class="pl-k">&lt;</span><span class="pl-k">class</span> <span class="pl-s"><span class="pl-pds">'</span>ga.Ga<span class="pl-pds">'</span></span><span class="pl-k">&gt;</span></pre></div>
<p>Succeed.</p>
      </blockquote>

@utensil commented on May 2, 2016

<blockquote>
          <p>I'll send a PR to correct instructions in INSTALL .</p>
      </blockquote>

@brombo commented on May 2, 2016

<blockquote>
          <p>Thanks for your feedback.  I think on OSX the directory where the python<br>
path files reside is not created when python is installed.  Are you<br>
using the default python that come with OSX or are your using another<br>
distribution, if so what distribution?</p>
      </blockquote>

@utensil commented on May 2, 2016

<blockquote>
          <p>I'm using <a href="http://conda.pydata.org/miniconda.html" rel="nofollow">MiniConda</a> which is a minimal distribution of <a href="https://www.continuum.io/why-anaconda" rel="nofollow">Anaconda</a> which is widely used.</p>
      </blockquote>

@utensil commented on May 2, 2016

<blockquote>
          <p>PR sent.</p>
      </blockquote>

@utensil commented on May 2, 2016 • 
edited 

<blockquote>
          <p>Though not related to this issue, I did notice something wrong in <code>terminal_check.py</code>:</p>
<div class="highlight highlight-source-python"><pre><span class="pl-c1">print</span> <span class="pl-s"><span class="pl-pds">'</span>-I*(grad^A) =<span class="pl-pds">'</span></span>, <span class="pl-k">-</span>o3d.E() <span class="pl-k">*</span> (grad <span class="pl-k">^</span> A)</pre></div>
<p>It should be <code>.I()</code> if I'm understanding it correctly.</p>
      </blockquote>

@utensil commented on May 7, 2016

<blockquote>
          <blockquote>
<p>"python setup.py test" not implemented (I don't really know hot to write<br>
a setup.py file).  You would need to run tests and examples manually<br>
(one at a time).  Also "test_test.py" uses old GA format and was not<br>
converted when I left sympy distribution.  There is no more module MV to<br>
import. Will fix<br>
test_test.py when I get time.</p>
</blockquote>
<p>I'm interested in writing a <code>setup.py</code> for <code>galgebra</code>, and add other essential parts to get <code>galgebra</code> into <a href="http://pypi.python.org/pypi/" rel="nofollow">PyPI</a> so it can be installed with <code>pip install galgebra</code>. Also I do have some time to fix the issues you mentioned above. Would you like it to be done? Because I think <code>galgebra</code> is a great library.</p>
      </blockquote>

@brombo commented on May 7, 2016

<blockquote>
          <p>I would greatly appreciate you doing such a thing.  Thank you very much.</p>
      </blockquote>

@utensil commented on May 8, 2016

<blockquote>
          <p>Great, then I would get started.</p>
      </blockquote>

@brombo closed this in brombo/galgebra#13 on May 11, 2016

---

From http://webcache.googleusercontent.com/search?q=cache:https://github.com/brombo/galgebra/issues/12

**Comment by eric-wieser** [comment]
Closed in the imported content already
